//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FairSharing) DeepCopyInto(out *FairSharing) {
	*out = *in
	if in.PreemptionStrategies != nil {
		in, out := &in.PreemptionStrategies, &out.PreemptionStrategies
		*out = make([]PreemptionStrategy, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FairSharing.
func (in *FairSharing) DeepCopy() *FairSharing {
	if in == nil {
		return nil
	}
	out := new(FairSharing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Integrations) DeepCopyInto(out *Integrations) {
	*out = *in
	if in.Frameworks != nil {
		in, out := &in.Frameworks, &out.Frameworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExternalFrameworks != nil {
		in, out := &in.ExternalFrameworks, &out.ExternalFrameworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelKeysToCopy != nil {
		in, out := &in.LabelKeysToCopy, &out.LabelKeysToCopy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Integrations.
func (in *Integrations) DeepCopy() *Integrations {
	if in == nil {
		return nil
	}
	out := new(Integrations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kueue) DeepCopyInto(out *Kueue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kueue.
func (in *Kueue) DeepCopy() *Kueue {
	if in == nil {
		return nil
	}
	out := new(Kueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kueue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueConfiguration) DeepCopyInto(out *KueueConfiguration) {
	*out = *in
	in.WaitForPodsReady.DeepCopyInto(&out.WaitForPodsReady)
	in.Integrations.DeepCopyInto(&out.Integrations)
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[string]EnabledOrDisabled, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ManageJobsWithoutQueueName != nil {
		in, out := &in.ManageJobsWithoutQueueName, &out.ManageJobsWithoutQueueName
		*out = new(ManageJobsWithoutQueueNameOption)
		**out = **in
	}
	if in.ManagedJobsNamespaceSelector != nil {
		in, out := &in.ManagedJobsNamespaceSelector, &out.ManagedJobsNamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.FairSharing.DeepCopyInto(&out.FairSharing)
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(EnabledOrDisabled)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueConfiguration.
func (in *KueueConfiguration) DeepCopy() *KueueConfiguration {
	if in == nil {
		return nil
	}
	out := new(KueueConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueList) DeepCopyInto(out *KueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kueue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueList.
func (in *KueueList) DeepCopy() *KueueList {
	if in == nil {
		return nil
	}
	out := new(KueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueOperandSpec) DeepCopyInto(out *KueueOperandSpec) {
	*out = *in
	in.OperatorSpec.DeepCopyInto(&out.OperatorSpec)
	in.Config.DeepCopyInto(&out.Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueOperandSpec.
func (in *KueueOperandSpec) DeepCopy() *KueueOperandSpec {
	if in == nil {
		return nil
	}
	out := new(KueueOperandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueStatus) DeepCopyInto(out *KueueStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueStatus.
func (in *KueueStatus) DeepCopy() *KueueStatus {
	if in == nil {
		return nil
	}
	out := new(KueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequeuingStrategy) DeepCopyInto(out *RequeuingStrategy) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(RequeuingTimestamp)
		**out = **in
	}
	if in.BackoffLimitCount != nil {
		in, out := &in.BackoffLimitCount, &out.BackoffLimitCount
		*out = new(int32)
		**out = **in
	}
	if in.BackoffBaseSeconds != nil {
		in, out := &in.BackoffBaseSeconds, &out.BackoffBaseSeconds
		*out = new(int32)
		**out = **in
	}
	if in.BackoffMaxSeconds != nil {
		in, out := &in.BackoffMaxSeconds, &out.BackoffMaxSeconds
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequeuingStrategy.
func (in *RequeuingStrategy) DeepCopy() *RequeuingStrategy {
	if in == nil {
		return nil
	}
	out := new(RequeuingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTransformation) DeepCopyInto(out *ResourceTransformation) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(ResourceTransformationStrategy)
		**out = **in
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTransformation.
func (in *ResourceTransformation) DeepCopy() *ResourceTransformation {
	if in == nil {
		return nil
	}
	out := new(ResourceTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	if in.ExcludeResourcePrefixes != nil {
		in, out := &in.ExcludeResourcePrefixes, &out.ExcludeResourcePrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Transformations != nil {
		in, out := &in.Transformations, &out.Transformations
		*out = make([]ResourceTransformation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForPodsReady) DeepCopyInto(out *WaitForPodsReady) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.BlockAdmission != nil {
		in, out := &in.BlockAdmission, &out.BlockAdmission
		*out = new(EnabledOrDisabled)
		**out = **in
	}
	if in.RequeuingStrategy != nil {
		in, out := &in.RequeuingStrategy, &out.RequeuingStrategy
		*out = new(RequeuingStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.RecoveryTimeout != nil {
		in, out := &in.RecoveryTimeout, &out.RecoveryTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForPodsReady.
func (in *WaitForPodsReady) DeepCopy() *WaitForPodsReady {
	if in == nil {
		return nil
	}
	out := new(WaitForPodsReady)
	in.DeepCopyInto(out)
	return out
}
