coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "vendor/"
  - "upstream/"
  - "bindata/"
  - "**/*_test.go"
  - "test/"
  - "hack/"
  - "pkg/generated/"
  - "**/zz_generated.*.go"
  - "cmd/"
  - "bundle/"
  - "manifests/"

github_checks:
  annotations: true