FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 as build

WORKDIR /workspace
COPY . .
WORKDIR /workspace/upstream/kueue
RUN ./build.sh

FROM registry.ci.openshift.org/ocp/builder:rhel-9-enterprise-base-multi-openshift-4.19
WORKDIR /
COPY --from=build /workspace/upstream/kueue/src/bin/manager /
COPY --from=build /usr/bin/lsof /usr/bin/lsof
USER 65532:65532

LABEL io.k8s.display-name="OpenShift Kueue Operand based on RHEL 9" \
      io.k8s.description="This is the Kueue operand component of OpenShift based on RHEL 9" \
      com.redhat.openshift.versions="v4.18-v4.19-v4.20-v4.21-v4.22-v4.23-v5.0" \
      io.openshift.tags="openshift,operand,kueue" \
      com.redhat.delivery.appregistry=true \
      maintainer="AOS Node team, <aos-node@redhat.com>"

ENTRYPOINT ["/manager"]
