kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-kueue-operator-networking
  namespace: openshift-kueue-operator
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
