kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-kueue-operator-networking
  namespace: openshift-kueue-operator
subjects:
  - kind: ServiceAccount
    name: openshift-kueue-operator
    namespace: openshift-kueue-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-kueue-operator-networking
