apiVersion: batch/v1
kind: Job
metadata:
  generateName: tas-job-
  namespace: kueue-tas-demo
  labels:
    kueue.x-k8s.io/queue-name: tas-hostname-lq
spec:
  parallelism: 2
  completions: 2
  template:
    metadata:
      annotations:
        kueue.x-k8s.io/podset-required-topology: kubernetes.io/hostname
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: test-container
        image: registry.access.redhat.com/ubi9/ubi-minimal:latest
        command: ["sh", "-c", "echo Hello Kueue; sleep 3600"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
