apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
  name: kueue-controller-manager-metrics-service
  namespace: openshift-kueue-operator
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
